export const USER_COMPONENT_NAME = {
  GRID: "Grid",
  CONTAINER: "Container",
  ROW: "Row",
  COLUMN: "Column",
  BUTTON: "Button",
  TEXT: "Text",
  PARAGRAPH: "Paragraph",
  INPUT: "Input",
  RADIOBOX: "Radiobox",
  CHECKBOX: "Checkbox",
  DATE_TIME_PICKER: "DateTimePicker",
  BREADCRUMBS: "Breadcrumbs",
  IMAGE: "Image",
  DIVIDER: "Divider",
  MENU: "Menu",
  SELECT: "Select",
  STATISTIC: "Statistic",
  SWITCH: "Switch",
  TAB: "Tab",
  TABLE: "Table",
  TAG: "Tag",
};
